# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_mgmt', '0005_auto_20160526_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='school',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
