# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_mgmt', '0011_auto_20160531_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(blank=True, choices=[('Re', 'Received'), ('P', 'Pending Interview'), ('I', 'Interviewed'), ('A', 'Accepted'), ('R', 'Rejected')], max_length=1, null=True),
        ),
    ]
