# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_mgmt', '0013_auto_20160531_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Pending Interview', 'Pending Interview'), ('Interviewed', 'Interviewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Received', max_length=1),
        ),
    ]
