# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_mgmt', '0015_auto_20160531_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='grad_year',
            field=models.IntegerField(null=True),
        ),
    ]
