# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_mgmt', '0016_auto_20160531_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='apptype',
        ),
        migrations.AddField(
            model_name='resume',
            name='Application_Type',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Full Time Employee', 'Full Time Employee')], max_length=30, null=True),
        ),
    ]
