# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_mgmt', '0018_resume_upload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='upload_file',
        ),
    ]
